name: Build Xamarin Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Java SDK 11
      run: |
        choco install openjdk11
        refreshenv

    - name: Set up Java SDK 11
      run: |
        echo "JAVA_HOME=C:\\Program Files\\OpenJDK\\openjdk-11.0.2" >> $Env:GITHUB_ENV
        echo "PATH=C:\\Program Files\\OpenJDK\\openjdk-11.0.2\\bin;$PATH" >> $Env:GITHUB_ENV

    - name: Verify Java SDK Installation
      run: |
        java -version
        echo $JAVA_HOME

    - name: Build Xamarin Android APK
      shell: pwsh
      run: |
        $vsPath = & "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        $msbuildPath = "$vsPath\\MSBuild\\Current\\Bin\\MSBuild.exe"
        & $msbuildPath Ble.Client/Ble.Client.sln /t:Restore /p:Configuration=Release
        & $msbuildPath Ble.Client/Ble.Client.Android/Ble.Client.Android.csproj /t:PackageForAndroid /p:Configuration=Release /p:JavaSdkDirectory="C:\\Program Files\\OpenJDK\\openjdk-11.0.2"

    - name: Publish APK
      uses: actions/upload-artifact@v2
      with:
        name: XamarinAndroidApp
        path: '**/*.apk'
