name: Build Xamarin Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'
    
    - name: Build Xamarin Android APK
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        msbuild /r /t:Restore,Build /p:Configuration=Release Ble.Client/Ble.Client.sln

    - name: Publish APK
      uses: actions/upload-artifact@v2
      with:
        name: XamarinAndroidApp
        path: '**/*.apk'
