name: Build Xamarin Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore Ble.Client/Ble.Client.sln

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/commandlinetools
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        mv $HOME/commandlinetools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "extras;google;m2repository" "extras;android;m2repository"

    - name: Set up environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Install Xamarin.Android workload
      run: |
        dotnet workload install android
        sudo apt-get install -y unzip zip
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip -d $HOME/Android/Sdk/ndk-bundle

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/Android/Sdk
        export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        dotnet build Ble.Client/Ble.Client.Android/Ble.Client.Android.csproj --configuration Release

    - name: Publish APK
      uses: actions/upload-artifact@v2
      with:
        name: XamarinAndroidApp
        path: '**/*.apk'
